1:
	mcs -out:program "./objective1.cs"
2:
	mcs -out:program "./objective2.cs"
2a:
	mcs -out:program "./objective2a.cs"
3:
	mcs -out:program "./objective3.cs"
run:
	mono program
clean:
	rm -rf program
