# Everything with 'wsl' prefix only works on windows in wsl
wsl1:
	wslview objective1.html
wsl2:
	wslview objective2.html
wsl3:
	wslview objective3.html

# GNU stuff should only work on linux
gnu1:
	firefox objective1.html
gnu2:
	firefox objective2.html
gnu3:
	firefox objective3.html

# Mac stuff should only work on MacOS
mac1:
	open -a "Google Chrome" objective1.html
mac2:
	open -a "Google Chrome" objective2.html
mac3:
	open -a "Google Chrome" objective3.html

