1:
	g++ -std=c++14 objective1.cpp -o program
2:
	g++ -std=c++14 objective2.cpp -o program
2a:
	g++ -std=c++14 -static-libgcc -static-libstdc++ objective2a.cpp -o program
3:
	g++ -std=c++14 objective3.cpp -o program
clean:
	rm -rf program
